_base_: default.yml
model:
  clip_model_name: ViT-B/16
  keep_cls: false
  keep_end_seq: false
  model_name: vit_base_patch16_dinov3.lvd1689m
  proj_class: dinov3_vitb_mlp_infonce
  proj_model: ProjectionLayer
  proj_name: dinov3_vitb_mlp_infonce
  resize_dim: 448
  type: DINOText
  use_avg_text_token: false
